### ISSUE TITLE
Why did you quit use an auto_route package?

### ISSUE THREAD

**Issue by rafekun** [bizz84/starter_architecture_flutter_firebase#19]
I'm thinking of using the auto_route package and would appreciate it if you could tell me why!

**Comment by bizz84** [comment]
The problem was that in my `main.dart` I have to rebuild the entire `MaterialApp` in response to stream events, and the widget in my initial route needs to rebuild with the new stream value.
If I use `ExtendedNavigator`, I can specify an `initialRoute`, as well as `initialRouteArguments`, but the `initialRoute` is built **only once**.
While this is is not necessarily an issue with `auto_route`, it doesn't behave in a predictable way for me in this case.
I also had some other issues with some test failing, that I couldn't resolve easily.

I still like`auto_route` and I think it works well in most cases. But when it doesn't, it's painful and causes hours of debugging. So I prefer to have **predictable** behavior by rolling out my navigation code.

**Comment by rafekun** [comment]
Thanks!
