### ISSUE TITLE
StreamBuilder stuck on ConnectionState.waiting

### ISSUE THREAD

**Issue by bpaperman** [bizz84/starter_architecture_flutter_firebase#30]
Hey Andrea,

I have a StreamBuilder with the stream below that queries documents isGreaterThanOrEqualTo DateTime.now()

If the query returns 1 or more results, everything works well. If, however, the results are empty (no documents exist with liveDate >= now), the stream hangs on ConnectionState.waiting and I get a perpetual CircularProgressIndicator. Any ideas? 

```
Stream<List<Object>> objectStreamAfterDate({@required DateTime afterDate}) => _service.collectionStream(
        path: FirestorePath.objects(),
        queryBuilder: (query) => query.where('isLive', isEqualTo: true)
          .where('isDeleted', isEqualTo: false)
          .where('liveDate', isGreaterThanOrEqualTo: DateTime.now()),
        builder: (data, documentId) => Object.fromMap(data, documentId),
        sort: (lhs, rhs) => rhs.createdDate.compareTo(lhs.createdDate),
      );
```

**Comment by bizz84** [comment]
That makes sense because all stream events that don't match the query are discarded, so the stream is in waiting state until you get a positive.
You can add an `initialData` with an empty value to your `StreamBuilder`. This will prevent the initial `CircularProgressIndicator`.
Is that good enough for your use case?

**Comment by bpaperman** [comment]
Thanks Andrea! That worked great. Thanks for the explanation.
